const languageConfig = {
  en: {
    chatView: {
      placeholder: 'Enter Message',
    },
    mainMenu: {
      playBtn: 'Play game',
      serverBtn: 'Join game',
      settingsBtn: 'Settings',
      quitBtn: 'Quit game',
    },
    quitConfirm: {
      confirmMessage: 'Are you sure?',
      yesBtn: 'Yes',
      noBtn: 'No',
    },
    serverMenu: {
      registeredAs: 'You are Registered as',
      passChanged: 'Password is changed',
      changePassRequest: 'Request to change password',
      loggedOut: 'Logged-Out',
      fail: 'fail',
      userIsAlreadyRegistered: 'The User is Already Registered',
      loginNoExist: 'The Login or the Password doesn\'t exist',
      wrongLoginOrPass: 'Wrong Login or Password',
      wrongOrExpiredToken: 'Wrong or Expired Token',
      wasWrongBD: 'Something was wrong with BD',
      nickname: 'name',
      password: 'password',
      newPassword: 'new password',
      logOut: 'Log-Out',
      connect: 'Connect',
      logIn: 'Log In',
      changePassword: 'Change Password',
      sendNewPassword: 'Send Password',
      or: 'or',
      signUp: 'Sign Up',
      backToMainMenu: 'Cancel',
      parseMessage: 'use only a-z, A-Z and 0-9, the length should be between 3 and 12',
      failMessage: 'already in use',
      exitServerGame: 'Disconnect',
    },
    settinsMenu: {
      langBtn: 'English',
      rangeLabel: 'distance: ',
      fovLabel: 'fov: ',
    },
  },
  ru: {
    chatView: {
      placeholder: 'Напишите сообщение',
    },
    mainMenu: {
      playBtn: 'Играть',
      serverBtn: 'Сетевая игра',
      settingsBtn: 'Настройки',
      quitBtn: 'Покинуть игру',
    },
    quitConfirm: {
      confirmMessage: 'Вы уверены?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },
    serverMenu: {
      registeredAs: 'Вы зарегистрированы как',
      passChanged: 'Пароль изменён',
      changePassRequest: 'Изменение пароля',
      loggedOut: 'Вы вышли из аккаунта',
      fail: 'Ошибка',
      userIsAlreadyRegistered: 'Пользователь уже зарегистрирован',
      loginNoExist: 'Такого пароля или логина не существует',
      wrongLoginOrPass: 'Неправильный пароль или логин',
      wrongOrExpiredToken: 'Неправильниый или просроченный токен',
      wasWrongBD: 'ошибка базы данных',
      nickname: 'имя',
      password: 'пароль',
      newPassword: 'новый пароль',
      connect: 'Подключиться',
      logOut: 'Выйти из аккаунта',
      logIn: 'Войти',
      changePassword: 'Изменить Пароль',
      sendNewPassword: 'Отправить Пароль',
      or: 'или',
      signUp: 'Зарегистрироваться',
      backToMainMenu: 'Отмена',
      parseMessage: 'используйте только a-z, A-Z и 0-9, длина должна быть от 3 до 12',
      failMessage: 'имя занято',
      exitServerGame: 'Отключиться',
    },
    settinsMenu: {
      langBtn: 'Русский',
      rangeLabel: 'дальность видимости: ',
      fovLabel: 'угол обзора: ',
    },
  },
};

export default languageConfig;
